default: &default
  adapter: postgresql

development:
  <<: *default
  database: commissulator_development
development_ciremoussa:
  <<: *default
  database: commissulator_development_ciremoussa

test:
  <<: *default
  database: commissulator_test
